### ISSUE TITLE
看起来是基于libuv改造的。

### ISSUE THREAD

**Issue by gogowishfly** [rocaltair/heap-timer#1]
Hello，

无意间看到你这个repo，从min-heap的头文件和实现的cc文件来看，是把libuv中的实现提炼出来了啊。
我也正想着提炼libuv或者libevent中的timer实现。

**Comment by rocaltair** [comment]
是的，不用要用sleep去跑，结合select或者epoll/kqueue精度更高更好用。

**Comment by gogowishfly** [comment]
赞！
